
- hosts: cloud-agents

  pre_tasks:
    
    # windows installation requires nssm
    - win_chocolatey:
        name: nssm
      when: ansible_os_family == "Windows"

  roles:
    - role: cloud-agent
      app_version: 12.4.5373     
