---

- name: verify os is correct
  fail:
    msg: "this role only supports mac os"
  when: ansible_os_family != "Darwin"

- name: install cloud agent
  include_tasks: tasks/install.yml
  when: state|default('present') == 'present'

- name: uninstall cloud agent
  include_tasks: tasks/uninstall.yml
  when: state|default('present') == 'absent'
